In [1]:
import numpy as np

In [3]:
#create - from lists
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.dtype,arr2.shape)

arr2D = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(arr2D,type(arr2D),arr2D.dtype,arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [5]:
#create
arr1 = np.zeros((2,3),dtype="int64") #prefill
print(arr1,arr1.shape)

arr2 = np.ones((2,3)) #prefil with one
print(arr2,arr2.shape)

arr3 = np.full((3,4) , 100) #prefil with any value
print(arr3,arr3.shape)

arr4 = np.eye(3) #Identity matrix
print(arr4,arr4.shape)

arr5 = np.arange(1,11,2)  #range elements
print(arr5,arr5.shape)

arr6 = np.linspace(1,100,4) #evenly spaced array
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)


In [7]:
#properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape) #dimension
print(arr.size) #total ele
print(arr.dtype) #data type
print(arr.ndim) 


float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [8]:
#Operations on arrays

arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped , reshaped.shape)

flattened = arr.flatten() # 2D => 1D
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
