In [2]:
import numpy as np

In [3]:
#create - from lists
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.dtype,arr2.shape)

arr2D = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(arr2D,type(arr2D),arr2D.dtype,arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [5]:
#create
arr1 = np.zeros((2,3),dtype="int64") #prefill
print(arr1,arr1.shape)

arr2 = np.ones((2,3)) #prefil with one
print(arr2,arr2.shape)

arr3 = np.full((3,4) , 100) #prefil with any value
print(arr3,arr3.shape)

arr4 = np.eye(3) #Identity matrix
print(arr4,arr4.shape)

arr5 = np.arange(1,11,2)  #range elements
print(arr5,arr5.shape)

arr6 = np.linspace(1,100,4) #evenly spaced array
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)


In [7]:
#properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape) #dimension
print(arr.size) #total ele
print(arr.dtype) #data type
print(arr.ndim) 


float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [8]:
#Operations on arrays

arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped , reshaped.shape)

flattened = arr.flatten() # 2D => 1D
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [4]:
#indexing
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[2])
print(arr[3])
idx = [0,1,2]
print(arr[idx])

print(arr[arr>2])

1
3
4
[1 2 3]


In [5]:
#Slicing
arr = np.array([1,2,3,4,5])

print(arr[1:4])

[2 3 4]


In [6]:
#Multi dimensional arrays

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D , axis = 0)
print(sum_of_columns)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]


In [8]:
#3D array

arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #2 X 3 X 2

print(arr3D,arr3D.shape)

#indexing
print(arr3D[1,1,0])

#Slicing
print(arr3D[:,0,:])  #1st row from both layers

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]


In [10]:
#broadcasting 

arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr + arr2)


[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


In [14]:
#Normalize

arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev

print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
